version: "3.9"
services:
    mysql:
        image: mysql:8.2.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - dbData:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        restart: always
        ports:
            - 8080:80
volumes:
    dbData:
